### ISSUE TITLE
does not work when ssgOptions:{dirStyle: "nested"}

### ISSUE THREAD

**Issue by ma-joel** [jbaubree/vite-ssg-sitemap#1]
the problem lies in here

https://github.com/jbaubree/vite-ssg-sitemap/blob/d50179bff473c0d45de1c6ec1d19d02cf1d655fc/src/index.ts#L16

in nested mode we need to remove the tailing `index.html`

**Comment by jbaubree** [comment]
Thanks for reporting this. v1.2 now supports this, you can pass nested option to true:
`onFinished() { generateSitemap({ nested: true }) }`

**Comment by jbaubree** [comment]
Update: nested option is not required anymore from v0.1.5
