### ISSUE TITLE
Proposal: Add an option to configure robots policies

### ISSUE THREAD

**Issue by xtatanx** [jbaubree/vite-ssg-sitemap#5]
With the current configuration the robots.txt policies either agree or disagree for the whole website. Some websites might need more control to give hints to crawlers. It would be good if we could pass this options as a configuration for the plugin.

I went ahead and created a PR #4 as a proposal on how to handles this, I am not well versed in typescript but this could be an approximation on how to gain more control to generate the robots.txt file.

**Comment by jbaubree** [comment]
I'm not sure about using generate-robotstxt library who has no type and was not updated for 2 years+.
I will work on a solution as soon as possible

**Comment by xtatanx** [comment]
That sounds good, I will be happy to help!

**Comment by xtatanx** [comment]
That sound good, I will be happy to help with this.

**Comment by jbaubree** [comment]
c68316539b73f185dfe4cb6893e8ee1ed3705cea ensures robots.txt policies configuration that you need :) you can upgrade to v0.2.0 and you will get it

**Comment by xtatanx** [comment]
Thank you very much! I appreciate your help

**Comment by xtatanx** [comment]
That sounds fare, I will be more than happy to help if needed, thanks for your fast responses!

Regards,
Jhonnatan
