### ISSUE TITLE
Add an option to set a block on specific routes in the sitemap

### ISSUE THREAD

**Issue by FranIsra** [jbaubree/vite-ssg-sitemap#52]
Currently I haven't found a way to block some routes from appearing in the sitemap. I think it would be nice if we could decide to block individual routes or a group of routes.

**Comment by jbaubree** [comment]
Sure ! I will work on ira asap 😁

**Comment by jbaubree** [comment]
You now download [v0.2.7](https://github.com/jbaubree/vite-ssg-sitemap/commit/196826fa24af7031a05404ac1f3324b4f3d93448). You have now exclude option.

**Comment by FranIsra** [comment]
Thank you very much!
