### ISSUE TITLE
v0.2.1 does not work, package files are missing

### ISSUE THREAD

**Issue by zguolee** [jbaubree/vite-ssg-sitemap#6]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/40738594/162364595-eb647713-1414-408a-87ea-029b76f5040d.png">

**Comment by jbaubree** [comment]
Oh, i'm sorry about that, just a mistake... Update to v0.2.2 and this will work again :)

**Comment by zguolee** [comment]
Thanks, it works.
