### ISSUE TITLE
Allow user to format their i18n url 

### ISSUE THREAD

**Issue by leoatfentech** [jbaubree/vite-ssg-sitemap#749]
I'm using this package to create a sitemap and robots.txt file for my website, it is working well except the part for i18n, because my formatting for i18n url does not match what you're using in the package, I can't get the right URLs.

**Comment by jbaubree** [comment]
Can you give more details about what you want to do and what you can't do?

**Comment by jbaubree** [comment]
Mmh, i think there is 2 i18n strategies, prefix or suffix:
- https://mywebsite.com/fr/my-path => prefix
- https://mywebsite.com/my-path/fr => suffix

What do you think about it?

**Comment by leoatfentech** [comment]
Yeah it looks good to me, seems like a easy solution to the problem ! 

Here's part of my sitemap

<url>
        <loc>https://test.com/cookies-policy</loc>
        <lastmod>2024-07-24T06:54:27.028Z</lastmod>
        <changefreq>yearly</changefreq>
        <priority>0.5</priority>
        <xhtml:link rel="alternate" hreflang="en" href="https://test.com/cookies-policy" />
        <xhtml:link rel="alternate" hreflang="fr" href="https://test.com/cookies-policy/fr" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://test.com/cookies-policy" />
    </url>
    <url>
        <loc>https://test.com/</loc>
        <lastmod>2024-07-24T06:54:27.028Z</lastmod>
        <changefreq>yearly</changefreq>
        <priority>1.0</priority>
        <xhtml:link rel="alternate" hreflang="en" href="https://test.com/" />
        <xhtml:link rel="alternate" hreflang="fr" href="https://test.com/fr" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://test.com/" />
    </url>

**Comment by jbaubree** [comment]
Fixed in `v0.8.0`
